/*
 * led.c
 *
 *  Created on: Sep 26, 2022
 *      Author: sigmadev
 */
#include "led.h"





void led_init(void){

	/*CURRENT LOW LED PA12  as output */
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODE12_0);
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODE12_1);

	/*CURRENT NORMAL LED PA11  as output */
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODE11_0);
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODE11_1);

	/*CURRENT HIGH  LED PA10  as output */
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODE10_0);
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODE10_1);

	/*SYS_RP LED PC6  as output */
	SET_BIT(GPIOC->MODER, GPIO_MODER_MODE6_0);
	CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE6_1);

	/* TEMPERATURE OK  LED PA9  as output */
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODE9_0);
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODE9_1);

	/* TEMPERATURE HIGH LED PA8  as output */
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODE8_0);
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODE8_1);

}
